Feature5 (#7)
* feature5

diff --git a/.github/workflows/pr-stage-to-main.yml b/.github/workflows/pr-stage-to-main.yml
--- a/.github/workflows/pr-stage-to-main.yml
+++ b/.github/workflows/pr-stage-to-main.yml
@@ -17,6 +17,8 @@ jobs:
         run: |
           echo 'testing ....'
           sleep 60
+          echo 'fail intentionally'
+          exit 1
 
       - name: Create Pull Request to main
         id: cpr
